export const SOCKET_URL = 'localhost:9000';

export const SOCKET_EVENTS = {
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGOUT: 'USER_LOGOUT',
  USER_SIGNUP: 'USER_SIGNUP',
  SEND_MESSAGE: 'CHAT/SEND_MESSAGE',
};
